### ISSUE TITLE
Data is compressed wrong

### ISSUE THREAD

**Issue by halehawk** [NCAR/SPERR#188] opened 2023-02-16 21:43 UTC
**Describe the bug**
I created a data file from MURaM 1152x512x256 data which only have two chunks, each chunk is 512x256x256. The SPERR cannot compress the second chunk correctly.

**To Reproduce**
[debug_work.pdf](https://github.com/NCAR/SPERR/files/10761112/debug_work.pdf)

**Expected and actual behavior**
A clear and concise description of what you expected to happen,
and what actually happened.
The reconstructed second chunk data should be the following:
2.4385039e-15 2.4872165e-15 2.5708369e-15 2.6486769e-15 2.6840206e-15
 2.6881527e-15 2.5566245e-15 2.2047681e-15 1.8494842e-15 1.6973415e-15]

But I got the following:
[-1.3500707e-11 -1.5191889e-11 -2.2858083e-11 -5.6626464e-11
 -6.3362651e-13  4.1816415e-11  1.1408697e-10  6.3748409e-11
 -1.1734481e-11 -6.9410054e-11]

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Compiler [e.g. Clang-12]
 - SPERR Version [The output of ./bin/version]

**Additional context**

**Comment by shaomeng** [comment] 2023-02-16 21:57
@halehawk Could you provide the following information to help me reproduce your bug?
1. Where is the data of question?
2. What operation (e.g., commands, parameters) you use? 
3. what output did you expect? 
4. What output did you observe?

**Comment by halehawk** [comment] 2023-02-16 22:06
It is shown in the pdf file.

On Thu, Feb 16, 2023 at 2:58 PM Samuel Li ***@***.***> wrote:

> @halehawk <https://github.com/halehawk> Could you provide the following
> information to help me reproduce your bug?
>
>    1. Where is the data of question?
>
> /glade/scratch/haiyingx/part_orig.bin

>
>    1. What operation (e.g., commands, parameters) you use?
>
> /glade/u/home/shaomeng/Git/SPERR-Matthias/install/bin/compressor_3d --omp
4 --dims 1024 256 256 --chunks 512 256 256 --psnr 100 --out_decomp_f
/glade/scratch/haiyingx/part_orig.decomp.bin
/glade/scratch/haiyingx/part_orig.bin

**Comment by shaomeng** [comment] 2023-02-16 22:16
Hi @halehawk  I see the data file you're using, and I also see the command you're using. However, I still don't know what you expect to see, and what the program actually shows. 
Please keep in mind that the more information you provide in a bug report, the easier the author can identify the bug, and the faster the bug is resolved.

**Comment by halehawk** [comment] 2023-02-16 22:18
It is in the bug report, the last part.

**Comment by shaomeng** [comment] 2023-02-16 22:24
@halehawk sorry, I cannot reproduce your report because of a lack of instructions.

I'd say that for this particular data, you told the compressor to compress at psnr=100 quality (--psnr 100) and the compressor achieves psnr=109 dB in the output file. The requirement is met so I don't see where the bug is.

**Comment by halehawk** [comment] 2023-02-16 22:33
So the second chunk data first ten values as follows:
orig

2.4385039e-15 2.4872165e-15 2.5708369e-15 2.6486769e-15 2.6840206e-15
2.6881527e-15 2.5566245e-15 2.2047681e-15 1.8494842e-15 1.6973415e-15]

your reconstructed
[-1.3500707e-11 -1.5191889e-11 -2.2858083e-11 -5.6626464e-11
-6.3362651e-13 4.1816415e-11 1.1408697e-10 6.3748409e-11
-1.1734481e-11 -6.9410054e-11]
They are supposed to be like that, right?

**Comment by halehawk** [comment] 2023-02-16 22:43
I think I found the problem, you didn't use chunking at all. That's why
your second chunk used the first chunk's mean as some kind of standard. So
those values which are around 1e-15 need not keep the precision at all.

**Comment by shaomeng** [comment] 2023-02-16 23:18
@halehawk The compressor takes as instruction one type of quality guarantee; in this case it is instructed to achieve PSNR=100. The compressor doesn't, however, provide any guarantee in terms of other quality measures. 

What you observed is unfortunate, because the values are off by 4 orders of magnitudes. However, the compressor still meets the PSNR requirements (it achieved PSNR=109), so this behavior is not considered a bug. 

Does it make sense now? If so, can I close this issue?

**Comment by halehawk** [comment] 2023-02-16 23:29
It is still a bug for me. I need to know if you still accept chunked data
for each of your C API, because I only can duplicate your results after
disabling the chunking for this data set. My python api only feeds each
chunk to each C API, but your command tool does something before you feed
in your compression API.
After I disabled the chunk, and didn't transpose the data before
compression, and transposed the data after decompression. I can get the
following plots:

**Comment by clyne** [comment] 2023-02-16 23:33
What about using point-wise-error tolerance mode instead of PSNR?

**Comment by shaomeng** [comment] 2023-02-16 23:59
@halehawk  Did you mean you observe different results using the CLI tools vs. the C API? If so, I'm afraid you made a mistake in your python code, because I see exact outputs between CLI tools and C API. 

Specifically, I use CLI commands below:
```
./bin/compressor_3d --omp 2 --dims 1024 256 256 --chunks 512 256 256 --psnr 100 --show_stats --out_decomp_f /glade/scratch/shaomeng/Feb16.output /glade/scratch/haiyingx/part_orig.bin
```
and C API executable below:
```
./3d.out /glade/scratch/haiyingx/part_orig.bin 1024 256 256 2 100
```
The output between these two commands are bit-for-bit identical, as shown below:
```
diff /glade/u/home/shaomeng/Git/SPERR-Matthias/examples/C_API/output.capi /glade/scratch/shaomeng/Feb16.output
```

I suggest that you take a look at the [sample program](https://github.com/NCAR/SPERR/blob/main/examples/C_API/3d.c) on how to use SPERR C API, and also look at the [C API documentation](https://github.com/NCAR/SPERR/wiki#sperr-c-api-1).

**Comment by shaomeng** [comment] 2023-02-17 00:00
> What about using point-wise-error tolerance mode instead of PSNR?

My understanding is that this isn't a usage problem, but a Python wrapper fails to give identical output problem...

**Comment by halehawk** [comment] 2023-02-17 00:08
I didn’t say C API command line tool is different from your compress_3d. I mean since using Matthias filter, your 2 chunks can not create same results as you compress them one by one. So is there way make sure my wrapper can have same capabilities? Because I feed in two chunks and get same results as they are compressed alone. So this data set is very useful to test the filter.Sent from my iPhoneOn Feb 16, 2023, at 5:00 PM, Samuel Li ***@***.***> wrote:﻿

What about using point-wise-error tolerance mode instead of PSNR?

My understanding is that this isn't a usage problem, but a Python wrapper fails to give identical output problem...

**Comment by shaomeng** [comment] 2023-02-17 02:59
> your 2 chunks can not create same results as you compress them one by one. 

As a compressor, all SPERR does is to make sure a user-provided quality is met. There's no guarantee that you compress them one by one or in any other combination will yield the same output.

> So is there way make sure my wrapper can have same capabilities?

If the same data and same parameters are given to the Python wrapper and C/C++ API, and the same outputs are produced, then your wrapper is correct and does have the same capabilities.

**Comment by halehawk** [comment] 2023-02-17 04:51
I confirmed if I compared my zarr file with your c api output per chunk.
They are bit-by-bit the same without Matthias Filter involved.
But if I use c_api to compress 2 chunks by one command, I cannot get the
same results.
You know why, because your c api gets inputs from the whole data set and
collects information from this whole array, for example, m_budget.
This is the only difference between your command line tools from my wrapper.

My zarr file is at /glade/scratch/haiyingx/part_orig_compchunk.zarr

Here is the screenshot of the comparison.

**Comment by shaomeng** [comment] 2023-02-17 07:13
> your c api gets inputs from the whole data set and collects information from this whole array, 

It is absolutely correct that SPERR takes global knowledge into consideration when performing compression on individual chunks. With this clarification, can I close this issue now?

**Comment by halehawk** [comment] 2023-02-17 15:42
Sure.Sent from my iPhoneOn Feb 17, 2023, at 12:13 AM, Samuel Li ***@***.***> wrote:﻿

your c api gets inputs from the whole data set and collects information from this whole array,

It is absolutely correct that SPERR takes global knowledge into consideration when performing compression on individual chunks. With this clarification, can I close this issue now?

**Comment by halehawk** [comment] 2023-02-17 15:49
But when we started project, you said all developement can base on chunks. Now I found out it cannot, and I have to find ways to make it work.Sent from my iPhoneOn Feb 17, 2023, at 8:42 AM, Haiying Xu ***@***.***> wrote:﻿Sure.Sent from my iPhoneOn Feb 17, 2023, at 12:13 AM, Samuel Li ***@***.***> wrote:﻿

your c api gets inputs from the whole data set and collects information from this whole array,

It is absolutely correct that SPERR takes global knowledge into consideration when performing compression on individual chunks. With this clarification, can I close this issue now?

**Comment by shaomeng** [comment] 2023-02-17 18:46
> But when we started project, you said all developement can base on chunks. Now I found out it cannot, and I have to find ways to make it work.

Sorry that you find something not working, but I still don't understand what exactly is not working for you. Let's move this discussion to an in person meeting.

**Closed by shaomeng** 2023-02-17 18:46 UTC
